[package]
name = "macevery"
version = "0.1.3"
edition = "2021"
description = "Everything-like local filename/path search for macOS"
license = "MIT"

[lib]
name = "macevery"
path = "src/lib.rs"

[[bin]]
name = "macevery"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
strip = true
